<?xml version="1.0" ?>
<model>
  <name>support_ship</name>
    <version>1.0</version>
    <sdf version="1.5">model.sdf</sdf>
    <author>
    </author>
    <description>A simple sea bottom</description>
</model>
